
version: '3'
services:
    zookeeper:
        image: wurstmeister/zookeeper:3.4.6
        ports:
           - "2181:2181"
    kafka:
       image: wurstmeister/kafka
        container_name: kafkacluster
        ports:
            - "9092:9092"
        expose:
            - "9093"
        environment:
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_LISTENERS:
            "INTERNAL://0.0.0.0:9093,\
             EXTERNAL://0.0.0.0:9092"
          KAFKA_ADVERTISED_LISTENERS:
            "INTERNAL://kafka:9093,\
             EXTERNAL://localhost:9092"
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP:
            "INTERNAL:PLAINTEXT,\
             EXTERNAL:PLAINTEXT"
          KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
